language: ruby
sudo: false
rvm:
  - 2.2
  - 2.3.0
  - 2.4.0
  - ruby-head
  - jruby-head

script:
  - bundle exec rspec
  - bundle exec rubocop

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
